apiVersion: v2
name: balloon-jobs
description: balloon jobs runner
type: application
version: 1.0.18
appVersion: 2.7.5-beta9
keywords:
- balloon
home: https://github.com/gyselroth/balloon
sources:
- https://github.com/gyselroth/balloon-helm
maintainers:
- name: Raffael Sahli
  email: sahli@gyselroth.com
